//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "MSModelObjectCommon.h"

@class MSModelObjectCache, MSModelObjectCacheGeneration, NSString;

@interface MSModelObjectCommon : NSObject
{
    MSModelObjectCacheGeneration *_modelObjectCacheGeneration;
    NSString *_objectID;
    MSModelObjectCache *_cache;
}

+ (id)generateObjectID;
+ (id)defaultName;
+ (void)clearInstanceCount;
+ (void)printInstanceCount:(id)arg1;
@property(readonly, nonatomic) BOOL hasModelObjectCacheGeneration;
@property(readonly) MSModelObjectCacheGeneration *modelObjectCacheGeneration;
- (BOOL)propertiesAreEqual:(id)arg1;
- (id)primitiveObjectID;
@property(copy, nonatomic) NSString *objectID; // @synthesize objectID=_objectID;
- (BOOL)hasObjectID;
- (id)generateObjectID;
- (void)setNilValueForKey:(id)arg1;
- (id)defaultName;
- (void)objectDidInit;
- (void)initializeUnsetObjectPropertiesWithDefaults;
- (void)performInitEmptyObject;
- (id)initWithNoSetup;
- (id)init;
@property(readonly, copy) NSString *description;
- (id)treeAsDictionary;
- (id)simpleTreeStructure;
- (id)treeStructure;
- (void)appendTreeStructureToString:(id)arg1 withIndent:(unsigned long long)arg2;
- (void)appendSimpleStructureToString:(id)arg1 withIndent:(unsigned long long)arg2;
- (void)recordDeallocation;
- (void)recordAllocation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

