//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MSSharedObjectContainer.h"

@interface MSSharedObjectContainer : _MSSharedObjectContainer
{
}

- (id)objectsSortedByName;
- (void)enumeratePotentialInstancesInContainer:(id)arg1 block:(id)arg2;
- (id)sharedObjectsInLayers:(id)arg1;
- (id)sharedObjectsInLayer:(id)arg1;
- (BOOL)resetSharedObjectInstance:(id)arg1;
- (void)syncInstance:(id)arg1 withTemplateInstance:(id)arg2;
- (void)synchroniseInstancesOfSharedObject:(id)arg1 withInstance:(id)arg2;
- (void)updateValueOfSharedObject:(id)arg1 byCopyingInstance:(id)arg2;
- (BOOL)updateInstancesOfSharedObject:(id)arg1 withValue:(id)arg2;
- (BOOL)syncSharedObjectWithInstance:(id)arg1;
- (void)unregisterInstance:(id)arg1;
- (void)registerInstance:(id)arg1 withSharedObject:(id)arg2;
- (unsigned long long)numberOfSharedObjects;
- (long long)indexOfSharedObject:(id)arg1;
- (id)sharedObjectAtIndex:(unsigned long long)arg1;
- (id)sharedObjectWithID:(id)arg1;
- (id)sharedObjectForInstance:(id)arg1;
- (BOOL)isSharedObjectForInstance:(id)arg1;
- (id)instancesOf:(id)arg1 inContainer:(id)arg2;
- (id)mergeSharedObjectWithName:(id)arg1 sharedObjectID:(id)arg2 instance:(id)arg3;
- (void)removeSharedObject:(id)arg1;
- (id)addSharedObjectWithName:(id)arg1 firstInstance:(id)arg2;
- (Class)sharedObjectClass;

@end

