//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSInspectorSection-Protocol.h"

@interface MSSpecialLayerViewController : NSViewController <MSInspectorSection, NSMenuDelegate>
{
    NSArray *_layers;
    NSArray *_layerInspectorControllers;
}

@property(retain, nonatomic) NSArray *layerInspectorControllers; // @synthesize layerInspectorControllers=_layerInspectorControllers;
@property(copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (id)views;
- (id)inspectorsWithProperContent;
- (id)layerOrContentsOfLayer:(id)arg1 ifKindOfClass:(Class)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

